# Generated by Django 6.0.3 on 2026-05-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('testScore', models.IntegerField()),
                ('degree', models.CharField(max_length=10)),
                ('score', models.FloatField()),
            ],
        ),
    ]
